### ISSUE TITLE
NPE with @Table(includeNullColumns=true and fieldsFormatSetAnnotation)

### ISSUE THREAD

**Issue by nikowitt** [TNG/JGiven#315] opened 2017-05-02 09:20 UTC
Using @Table with includeNullColumns = true and a fieldsFormatSetAnnotation results in a NPE when a column value really has null values:
```
java.lang.NullPointerException
	at com.tngtech.jgiven.report.text.PlainTextTableWriter.hasNewline(PlainTextTableWriter.java:106)
	at com.tngtech.jgiven.report.text.PlainTextTableWriter.handleNewLines(PlainTextTableWriter.java:63)
	at com.tngtech.jgiven.report.text.PlainTextTableWriter.writeDataTable(PlainTextTableWriter.java:29)
	at com.tngtech.jgiven.report.text.PlainTextScenarioWriter.printDataTable(PlainTextScenarioWriter.java:178)
	at com.tngtech.jgiven.report.text.PlainTextScenarioWriter.printStep(PlainTextScenarioWriter.java:139)
	at com.tngtech.jgiven.report.text.PlainTextScenarioWriter.visit(PlainTextScenarioWriter.java:93)
	at com.tngtech.jgiven.report.model.StepModel.accept(StepModel.java:77)
	at com.tngtech.jgiven.report.model.ScenarioCaseModel.accept(ScenarioCaseModel.java:73)
	at com.tngtech.jgiven.report.model.ScenarioModel.accept(ScenarioModel.java:28)
	at com.tngtech.jgiven.report.text.PlainTextReporter.visit(PlainTextReporter.java:68)
	at com.tngtech.jgiven.report.model.ScenarioModel.accept(ScenarioModel.java:26)
	at com.tngtech.jgiven.report.model.ReportModel.accept(ReportModel.java:45)
	at com.tngtech.jgiven.report.text.PlainTextReporter.write(PlainTextReporter.java:51)
	at com.tngtech.jgiven.report.impl.CommonReportHelper.finishReport(CommonReportHelper.java:30)
	at com.tngtech.jgiven.junit.JGivenClassRule.finished(JGivenClassRule.java:22)
	at org.junit.rules.TestWatcher.finishedQuietly(TestWatcher.java:117)
	at org.junit.rules.TestWatcher.access$400(TestWatcher.java:46)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:64)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:193)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```
using includeNullColumns=false not using fieldsFormatSetAnnotation solves this issue.

Best regards,
Niko

UPDATE: it seems that includeNullColumns not always solved the issue. Using a @NamedFormat on a 
update: it seems that includeNullColumns not always solved the issue. Using a @NamedFormat on anull value (even when null is covered in the formatter implementation) still triggers the NPE.

**Comment by janschaefer** [comment] 2017-05-02 16:50
thanks for reporting!

**Comment by janschaefer** [comment] 2017-05-07 17:41
Issue is fixed by d2fe787128c9e82d045da60a373cc39395f409bc

**Comment by nikowitt** [comment] 2017-05-08 04:52
Thanks very much! I've tried my test once more. The test itself seems to run smoothly now, but it seems that there is still a similar issue during the report creation:

```
java.lang.NullPointerException
	at com.tngtech.jgiven.report.text.PlainTextTableWriter.getColumnSpecs(PlainTextTableWriter.java:119)
	at com.tngtech.jgiven.report.text.PlainTextTableWriter.writeDataTable(PlainTextTableWriter.java:31)
	at com.tngtech.jgiven.report.text.PlainTextScenarioWriter.printDataTable(PlainTextScenarioWriter.java:178)
	at com.tngtech.jgiven.report.text.PlainTextScenarioWriter.printStep(PlainTextScenarioWriter.java:139)
	at com.tngtech.jgiven.report.text.PlainTextScenarioWriter.visit(PlainTextScenarioWriter.java:93)
	at com.tngtech.jgiven.report.model.StepModel.accept(StepModel.java:77)
	at com.tngtech.jgiven.report.model.ScenarioCaseModel.accept(ScenarioCaseModel.java:73)
	at com.tngtech.jgiven.report.model.ScenarioModel.accept(ScenarioModel.java:28)
	at com.tngtech.jgiven.report.text.PlainTextReporter.visit(PlainTextReporter.java:68)
	at com.tngtech.jgiven.report.model.ScenarioModel.accept(ScenarioModel.java:26)
	at com.tngtech.jgiven.report.model.ReportModel.accept(ReportModel.java:45)
	at com.tngtech.jgiven.report.text.PlainTextReporter.write(PlainTextReporter.java:51)
	at com.tngtech.jgiven.report.impl.CommonReportHelper.finishReport(CommonReportHelper.java:30)
	at com.tngtech.jgiven.junit.JGivenClassRule.finished(JGivenClassRule.java:22)
	at org.junit.rules.TestWatcher.finishedQuietly(TestWatcher.java:117)
	at org.junit.rules.TestWatcher.access$400(TestWatcher.java:46)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:64)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:193)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

Best regards,
Niko

**Comment by janschaefer** [comment] 2017-05-08 06:07
Ok, I will create a more complete test case.

**Comment by janschaefer** [comment] 2017-05-08 06:22
I could not reproduce the issue. Could you provide a minimal example that causes the problem?

**Comment by nikowitt** [comment] 2017-05-08 06:23
Sure, I hope I can do this tomorrow morning.

**Comment by janschaefer** [comment] 2017-05-08 06:26
I think it might depend on your formatter implementation. The problem might be that your formatter implementation returns null where it should not. This, however, is also not documented in the API.

**Comment by nikowitt** [comment] 2017-05-08 06:28
Oh, this indeed could be the case - let me should doublecheck this.

**Comment by nikowitt** [comment] 2017-05-08 06:31
Very good catch, this indeed is the case, I'm returning null instead of blank in one used formatter. Changing this solves the issue. Maybe the exception thrown there could be improved to give a hint in the right direction?

**Comment by janschaefer** [comment] 2017-05-08 06:44
Yes, definitely. And the documentation should be more clear about this.

**Closed by janschaefer** 2017-05-08 06:44 UTC
Labels: bug, core
