### ISSUE TITLE
 HTML Report: Back Button does not work after searching

### ISSUE THREAD

**Issue by cirquit** [TNG/JGiven#281] opened 2016-12-27 11:04 UTC

**Comment by cirquit** [comment] 2017-01-18 11:23
Can't reproduce this now, maybe after port to the extra module fixed this.

**Comment by janschaefer** [comment] 2017-01-19 19:26
I can still reproduce this on the master branch.

**Comment by cirquit** [comment] 2017-01-31 15:34
After some tests it looks like this is not only a problem of the search functionality, but an angular one. After first loading the page, the history has the length 1.

```javascript
>> history
History { length: 1, scrollRestoration: "auto", state: null }
```
After accessing `All Scenarios`:
```javascript
>> history
History { length: 3, scrollRestoration: "auto", state: null }
```
And now the clicking the back button just jumps to the current page without ever greying out. All other Tags or Classes afterwards allow to jump to the previous site.

When the Search is accessed, or any Scenarios or Classes, a similar thing happens, but the increment of the `length` attribute of the `history` is only 1, thus `length : 2`. And once you try to jump back, then the back button greys out, but you stay on the same page. 

The only way to get to the welcome page is to use `history.go(0)`, which somehow still stores the initial page, but isn't accessible through the back button.

**Comment by cirquit** [comment] 2017-02-01 18:27
As discussed offline, this is problem probably arises because of loading page if any link is clicked where the pageination is used. This way the intermediate url is saved and one can't got back.

The proposed solution would be to append to every link the pageination string which is always the same `?page=1&itemsPerPage=40`. It seemed that, if it wasn't need it just got deleted.

**Comment by janschaefer** [comment] 2017-08-20 08:21
Closing this issue here, because it will be handled in https://github.com/jgiven/jgiven-html-app/issues/3

**Closed by janschaefer** 2017-08-20 08:21 UTC
Labels: bug, HTML Report, minor
