### ISSUE TITLE
ExpectedScenarioState Rule not available in BeforeStage

### ISSUE THREAD

**Issue by jangalinski** [TNG/JGiven#364] opened 2018-08-15 15:38 UTC
I have an externalResourceRule in my Test that I provide via `@Rule @ProvidedScenarioState`.

I have access to the rule in my Steps#methods. But during the `@BeforeStage` execution, it is still null.

That's not nice, because now I have to workaround with `@Hidden` given steps.

**Comment by janschaefer** [comment] 2018-08-15 19:41
which JUnit version do you use?

**Comment by jangalinski** [comment] 2018-08-15 20:16
4.12 and jgiven 0.16

**Comment by janschaefer** [comment] 2018-08-15 20:45
I cannot reproduce this. My test is green :-). See linked test case.

**Comment by janschaefer** [comment] 2019-09-02 21:01
Closing for now. Feel free to reopen.

**Closed by janschaefer** 2019-09-02 21:01 UTC
Labels: JUnit, waiting for additional input
