### ISSUE TITLE
Parameter unexpectedly appears in two columns

### ISSUE THREAD

**Issue by nikowitt** [TNG/JGiven#163] opened 2015-11-04 14:21 UTC
Hi Jan,
```
	@Test
	@JIRAIssue("SUMA-932")
	@DataProvider({
			USER_SYSTEM + _ + FALSE + _ + TRUE,
			USER_ADMINISTRATOR + _ + FALSE + _ + TRUE,
			USER_MANAGER + _ + FALSE + _ + TRUE,
			USER_BUYER_AUDITOR + _ + FALSE + _ + TRUE
	})
	public void validate_read_access(String userName, boolean isContactOfSupplier, boolean isAllowed) throws Exception {
		given().new_project_performance_where_user_$_$_added_as_supplier_contact(userName, isContactOfSupplier)
				.and().logged_in_user(userName);
		when().user_reads_entity();
		then().access_is_$(isAllowed);
	}
```

renders

```
Test Class: com.sobis.suma.tests.security.ProjectPerformanceSecurityTest

 Scenario: validate read access

   Given new project performance where user <userName> <isSupplierContact> added as supplier contact
     And logged in user <userName2>
    When user reads entity
    Then access is <expectSuccess>

  Cases:

    | # | userName                 | isSupplierContact | userName2                | expectSuccess | Status  |
    +---+--------------------------+-------------------+--------------------------+---------------+---------+
    | 1 | "system"                 | is not            | "system"                 | granted       | Success |
    | 2 | "SUMA Admin"             | is not            | "SUMA Admin"             | granted       | Success |
    | 3 | "SUMA Manager"           | is not            | "SUMA Manager"           | granted       | Success |
    | 4 | "SUMA Auditor Buyer"     | is not            | "SUMA Auditor Buyer"     | granted       | Success |

```

Since the same field "userName" is used in the test method signature and the formatting of the fields is the same (@Quoted), I expect userName2 to not appear at all.

Best regards,
Niko

**Comment by janschaefer** [comment] 2015-11-04 15:02
Hi, yes that is a known issue, but a complete example was missing to reproduce it (#140). I will have a look.

**Comment by janschaefer** [comment] 2015-11-05 06:28
The good news is, I can reproduce the problem and also found the reason for the problem. The bad news is, it is not very is to fix. In fact, I will have to rewrite a large portion of the algorithm that determines which arguments can be merged to the same parameter. The problem is the `@Quoted` annotation. In fact, any formatting applied to step arguments will prevent these arguments to be merged to the same parameter when they are used twice or more in the same scenario.

**Comment by nikowitt** [comment] 2015-11-05 06:46
I can confirm that it works fine when I remove the @Quoted parameter.

**Closed** 2015-11-07 19:45 UTC
Labels: bug, core
