### ISSUE TITLE
attachment not reported on failed step

### ISSUE THREAD

**Issue by adrian-herscu** [TNG/JGiven#408] opened 2019-05-30 08:55 UTC
```
    @NestedSteps
    public SELF when_doing_something(...) {
        try {
            return when_doing_1()
                .and().when_doing_2();
        } finally {
            attachScreenshot(browser.get());
        }
    }
```
If the above succeeds then the screenshot appears in the report on the `when_doing_something` step; if it fails, the screenshot is created, I can find it in the JSON report and as a file in the `html\data\attachments` directory for the relevant test class, but it is not rendered in the HTML report :(

**Comment by janschaefer** [comment] 2019-06-05 18:52
I think this is a duplicate of #366

**Closed by janschaefer** 2019-06-05 18:52 UTC
Labels: HTML App, bug
