### ISSUE TITLE
HTML5 Report: Accumulate tags

### ISSUE THREAD

**Issue by clementheliou** [TNG/JGiven#80] opened 2015-06-19 10:02 UTC
Currently, we can select scenarios related to one given tag by clicking on it.
But we're not able to select scenarios related to a selection of tags.

Let's say we have these tags:
* Customer -> this a high-level feature tag;
* Account -> this is a more specific feature tag that could be used inside another high-level feature;
* Listed -> this is a customer specificity that could be used inside another high-level feature.

If I filter scenarios by one of these tags, I do not have the ones I'm looking for.
A possible solution would be the accumulation of tags: `Customer AND Account AND Listed`.
We could also think about a more flexible mechanism language: `Customer AND (Account OR Listed)`.

**Comment by janschaefer** [comment] 2015-06-19 10:08
Regarding the AND case you can currently use the search for that, because it will search for all occurrences. The OR case is not possible yet. It could be solved using an improved client-side search engine (see #53).

**Comment by clementheliou** [comment] 2015-06-19 11:29
Regarding the AND case, the search feature is incomplete.
It returns the scenarios having both the three tags but also the ones having only one (or two) of them, which is undesired.

Will this use case be solved using an improved client-side search engine?

**Comment by janschaefer** [comment] 2015-06-19 11:34
Are you sure? For example, if I search for 'Tags JUnit' I only get scenarios which have 'Tags' and 'JUnit':

http://jgiven.org/jgiven-report/html5/#/search/Tags%20JUnit

**Comment by clementheliou** [comment] 2015-06-19 11:46
Ok, I got it! 
My tags have spaces in their values and share a common part.

* Account Management
* Account Administration

If I search for 'Customer Account Management Listed', it also returns the scenarios with 'Account Administration' tag.

**Comment by janschaefer** [comment] 2015-06-19 13:10
Ok. I see :-)

**Comment by janschaefer** [comment] 2015-06-22 21:18
Created #82 for searching for words with whitespace

**Comment by janschaefer** [comment] 2015-07-20 05:51
Do you think this issue can be closed now with the introduction of filtering by tags?

**Comment by clementheliou** [comment] 2015-07-21 13:44
Intrinsically, the filtering by tags feature resolves this issue.
However, there is some kind of troubleshooting with it.

Let's try with the JGiven documentation: http://jgiven.org/jgiven-report/html5/#/tag/Feature/JUnit
Randomly, scenarios are not updated with the selected tags (for examples Tags & TestNG).

**Comment by janschaefer** [comment] 2015-07-21 14:39
Mmh. For me it works as (I) expected. Could you explain in more detail what is wrong?

**Comment by clementheliou** [comment] 2015-07-21 15:43
Let's say I'm looking at the JUnit feature: http://jgiven.org/jgiven-report/html5/#/tag/Feature/JUnit
When I accumulate/select the Tags & TestNG values inside the Tags dropdown, the displayed scenarios are not always updated. That means, randomly, unrelated scenarios are still displayed.

It looks like a refresh issue but seems to appears randomly.

**Comment by janschaefer** [comment] 2015-07-21 15:57
Ok. That is strange and should not happen ;-). Which browser are you using?

**Comment by clementheliou** [comment] 2015-07-21 16:18
I'm using Chrome version 38.0.2125.104

**Comment by janschaefer** [comment] 2015-07-21 17:02
With Chrome 43.0.2357.125 on Linux, I cannot reproduce it. Could you please test it in another browser to see whether this is browser-specific? And could you take a screenshot of the wrong page?

**Comment by clementheliou** [comment] 2015-07-22 07:33
I can reproduce this behavior with Firefox 24.1.1 ESR.
See below a screenshot.
![troubleshooting_tags](https://cloud.githubusercontent.com/assets/10561933/8820298/799dae10-3054-11e5-9dff-e135308cd828.PNG)

**Comment by janschaefer** [comment] 2015-07-22 07:52
Ok. Beside the fact that the layout is not that good, because of the smaller window size (that should be fixed) this is what I also see :-). Maybe we have a different understanding of what should be shown. The point is that the selection of tags is actually an 'or' relation and not an 'and' relation. Thus if you select 'Tags' and 'TestNG' you will see all scenarios that have either the 'Tags' tag or the 'TestNG' tag or both. But I see that this might be confusing. Do you think it would make more sense to have an 'and' relation?

**Comment by janschaefer** [comment] 2015-07-22 08:11
Actually I must admit that I wanted to follow the GitHub behavior when using labels. Somehow I thought that this was an or-relation, but actually it is an and-relation. So I guess using an and-relation is more intuitive.

**Comment by clementheliou** [comment] 2015-07-22 08:56
I was expecting an and-relation but I have to admit that using the or one is also a valid scenario.
If you decide to add the and-relation, this issue could be closed.

**Comment by janschaefer** [comment] 2015-07-22 13:10
Ok. I will have to think about that :-)

**Comment by janschaefer** [comment] 2015-08-02 07:12
For now I decided to change the or to an and-relation, because it is typically the case that you want to narrow down the number of scenarios. The change will be in v0.8.0.

**Comment by clementheliou** [comment] 2015-08-05 19:44
Nice! Thanks.

**Comment by Airblader** [comment] 2016-06-19 18:48
@janschaefer What is the status of this? It almost sounds like this has been "fixed", but there's no linked commits or information on what else would have to be done.

**Comment by janschaefer** [comment] 2016-06-23 09:10
Maybe I really forgot to close this issue :-). @clementheliou do you think we can close this?

**Comment by clementheliou** [comment] 2016-06-23 21:45
@janschaefer Yes, you can.
This issue has been fixed a long time ago with the switch from the OR relation to the AND one.

**Closed** 2016-06-23 21:45 UTC
Labels: enhancement, HTML Report

**Comment by janschaefer** [comment] 2016-06-24 08:21
Great thx!
