### ISSUE TITLE
cannot get html report when a test failed

### ISSUE THREAD

**Issue by rolfschumacher** [TNG/JGiven#251] opened 2016-11-13 18:31 UTC
When running a test with a failure I do get a json file but I will not get a html report.
Is that intended or do I do something wrong?
This is my pom.xml snippet:
```
      <plugin>
        <groupId>com.tngtech.jgiven</groupId>
        <artifactId>jgiven-maven-plugin</artifactId>
        <version>${jgiven-maven-plugin.version}</version>
        <executions>
          <execution>
            <phase>test</phase>
            <goals>
              <goal>report</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <format>html</format>
        </configuration>
      </plugin>

```

**Comment by janschaefer** [comment] 2016-11-14 06:46
That is expected behavior. Maven stops executing when the tests fail and thus the JGiven HTML report is not generated. You can prevent that with the -fea flag of maven on the command line.

**Comment by janschaefer** [comment] 2016-11-14 06:50
As an alternative you can also execute the JGiven report on its own after the failing tests. This might be more appropriate on a CI server. `mvn -Dmaven.test.skip=true jgiven:report`

**Comment by janschaefer** [comment] 2016-12-17 19:58
Closing the issue for now. If you have any further questions, just let me know.

**Closed by janschaefer** 2016-12-17 19:58 UTC
Labels: question, waiting for additional input

**Comment by corbym** [comment] 2021-07-27 13:26
This seems.. wrong.. given that jgivens has a "failure" state it can be in. Having an extra step to generate the report seems crazy. HTML reports should always be generated.

Could I suggest that the report generation is too dependent on the plugin? A report should be generated after tests have run regardless.

**Comment by l-1squared** [comment] 2021-07-28 05:22
Hi @corbym 

the HTML report and AsciiDoc generation are separated, because we wanted the modules to be independent from the core. Also this guarantees that the tests have run completely, which makes it easier to make use of the functionality like sorting for errors or tagging. 

I expect the integration of the report genereators to require a good deal of restructuring of JGiven, with a potential for nasty obstacles on the way. As there is a viable workaround that only requires users to set some flags during maven execution, I would opt to  keep the structure as it is.

There is however a basic text report that is integrated into the core and is supposed to be executed during JGiven Scenarios. If you want to have some guaranteed output, feel free to turn it on.
