### ISSUE TITLE
Powermock

### ISSUE THREAD

**Issue by nnar1o** [TNG/JGiven#365] opened 2018-09-18 09:53 UTC
When I try to create test using powermock (class annotated with `@RunWith(PowerMockRunner.class)`)
Jgiven logging does not work and json report is not generated

**Comment by ahus1** [comment] 2018-09-18 13:44
Could you please publish a minimal example that shows the problem? This would help to investigate what's going wrong.

**Comment by nnar1o** [comment] 2018-09-18 14:14
sample project: https://github.com/nnar1o/powermock-jgiven-test

**Comment by janschaefer** [comment] 2018-09-22 10:08
Thanks for the example. I can confirm that it is not working.

**Comment by janschaefer** [comment] 2018-09-22 10:31
I reopen the issue, because the mentioned workaround of adding `@PowerMockRunnerDelegate( BlockJUnit4ClassRunner.class )` is also not working. The workaround enables Class Rules again, but due to some other PowerMock behavior it is not working either.

**Comment by janschaefer** [comment] 2018-09-22 10:38
Issue will be fixed with v0.16.1 and the mentioned workaround.

**Closed** 2018-09-22 10:37 UTC
Labels: JUnit, bug

**Comment by f3mshep** [comment] 2018-10-15 20:08
I was able to resolve this issue by annotating the test class with the following:
`@RunWith(PowerMockRunner.class)
@PowerMockRunnerDelegate(BlockJUnit4ClassRunner.class)`
