### ISSUE TITLE
Injected stages do not go well together with injected scenario states.

### ISSUE THREAD

**Issue by koenusz** [TNG/JGiven#203] opened 2016-04-18 10:34 UTC
My Situation:
Some steps in your testsuite are usable by many tests. For instance logging into your application. Ideally you would like to program this functionality once and reuse it throughout your testsuite. I found that injecting scenario stages is quite convenient for this purpose. However I found that scenario State is not properly transferred to the parent stage.

An example of the situation:

```
public class MyFeatureSteps extends Stage<MyAppSteps>{	
	
	@ScenarioStage
	LoginSteps loginSteps;
	
	@ExpectedScenarioState
	int newUserId; //The newUserId is not injected here!!
	
	
	public GivenLessomplanSteps a_new_user() {
		loginSteps.a_new_user();
		return self();
	}
	
	public GivenLessomplanSteps the_user_sets_up_my_feature(){
			FeatureFactory.setUp(newUserId);
	}
}	
public Class LoginSteps extends Stage<LoginSteps>{

	@ProvidedScenarioState
	int newUserId;

	public LoginSteps a_new_user() {
		
		newUserId = LoginService.myLoginMethod();	
		return self();
	}		
}
```
The reason for this behavior lies in the way the ValueInjector, which is the class that manages the injected states, gets called. The method readValues is called from a method with the BeforeScenario Annotation. This method is not called when execution is handed over from the child stage to the parent stage thus failing to update the scenario state.

A workaround for this problem is to provide accessors to the state variable and call the get method to update the parent's state.

**Comment by albertofaci** [comment] 2016-04-18 14:24
I just reported the same thing #202 :)
I'm debugging at the moment. The framework instantiates `loginSteps` for you, but the StepMethodInterceptor would not kick in in when you update `newUserId` and update it in `MyFeatureSteps`

**Comment by janschaefer** [comment] 2016-04-18 20:15
Yes, this problem is known to me. State transfer currently doesn't work for stages injected into other stages, because the precise semantics is somehow hard to define. This is thus also no documented feature. The point here would be that on calling the injected state the state of the parent stage must be read and the child stage updated. When the call comes back the state of the parent stage must be updated again. For this I somehow have to track the stack of stages. This might be technically possible, however, I wonder whether this is easy to understand.

**Comment by janschaefer** [comment] 2016-04-18 20:17
As two people had the same intuition, I think this might actually be intuitive :-) I have to think about that a bit, maybe I will create some experimental annotation/feature.

**Comment by koenusz** [comment] 2016-04-19 09:16
Maybe the issue can be solved by using a publish/subscribe mechanism. That way when the value gets updated in the `ValueInjector` you can use callbacks to update the value of all the statevariables in the testsuite.

**Comment by koenusz** [comment] 2016-04-19 09:56
```
package jgiven;



import java.lang.annotation.Annotation;
import java.lang.reflect.Field;
import java.util.Collection;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.google.common.collect.Maps;
import com.tngtech.jgiven.Stage;
import com.tngtech.jgiven.annotation.ExpectedScenarioState;
import com.tngtech.jgiven.annotation.ProvidedScenarioState;
import com.tngtech.jgiven.annotation.ScenarioState;
import com.tngtech.jgiven.annotation.ScenarioState.Resolution;
import com.tngtech.jgiven.exception.AmbiguousResolutionException;
import com.tngtech.jgiven.impl.inject.ValueInjectorState;
import com.tngtech.jgiven.impl.util.FieldCache;

/**
 * Used by Scenario to inject and read values from objects.
 */
public class ValueInjector {
    private static final Logger log = LoggerFactory.getLogger( ValueInjector.class );

    private final ValueInjectorState state = new ValueInjectorState();

    /**
     * Caches all classes that have been already validated for ambiguous resolution.
     * This avoids duplicate validations of the same class.
     */
    private static final ConcurrentHashMap<Class<?>, Boolean> validatedClasses = new ConcurrentHashMap<Class<?>, Boolean>();

    /**
     * @throws AmbiguousResolutionException when multiple fields with the same resolution exist in the given object
     */
    @SuppressWarnings( "unchecked" )
    public void validateFields( Object object ) {
        if( validatedClasses.get( object.getClass() ) == Boolean.TRUE ) {
            return;
        }

        Map<Object, Field> resolvedFields = Maps.newHashMap();

        for( Field field : getScenarioFields( object ) ) {
            field.setAccessible( true );
            Resolution resolution = getResolution( field );
            Object key = null;
            if( resolution == Resolution.NAME ) {
                key = field.getName();
            } else {
                key = field.getType();
            }
            if( resolvedFields.containsKey( key ) ) {
                Field existingField = resolvedFields.get( key );
                throw new AmbiguousResolutionException( "Ambiguous fields with same " + resolution + " detected. Field 1: " +
                        existingField + ", field 2: " + field );
            }
            resolvedFields.put( key, field );
        }

        validatedClasses.put( object.getClass(), Boolean.TRUE );
    }

    private List<Field> getScenarioFields( Object object ) {
        return FieldCache.get( object.getClass() ).getFieldsWithAnnotation( ScenarioState.class, ProvidedScenarioState.class,
            ExpectedScenarioState.class );
    }

    @SuppressWarnings( "unchecked" )
    public void readValues( Object object ) {
        validateFields( object );
        for( Field field : getScenarioFields( object ) ) {
            try {
                Object value = field.get( object );
                updateValue( field, value );
                log.debug( "Reading value {} from field {}", value, field );
            } catch( IllegalAccessException e ) {
                throw new RuntimeException( "Error while reading field " + field, e );
            }
        }
    }

    @SuppressWarnings( "unchecked" )
    public void updateValues( Object object ) {
        validateFields( object );
        for( Field field : getScenarioFields( object ) ) {
            try {
                Object value = getValue( field );
                if( value != null ) {
                    field.set( object, value );
                    log.debug( "Setting field {} to value {}", field, value );
                }
            } catch( IllegalAccessException e ) {
                throw new RuntimeException( "Error while update field " + field, e );
            }
        }
    }
    
    private void subscriberCallback(String fieldName)
    {
    	Collection<Stage> subscribers = state.getSubscribers(fieldname);
    	for(Stage stage : subscribers)
    	{
    		readValues(stage);
    	}
    	
    }

    public <T> void injectValueByType( Class<T> clazz, T value ) {
        state.updateValueByType( clazz, value );
    }

    public <T> void injectValueByName( String name, T value ) {
        state.updateValueByName( name, value );
    }

    private void updateValue( Field field, Object value ) {
        Resolution resolution = getResolution( field );
        Class<?> type = field.getType();
        if( resolution == Resolution.NAME ) {
            String name = field.getName();
            state.updateValueByName( name, value );
        } else {
            state.updateValueByType( type, value );
        }
    }

    private Object getValue( Field field ) {
        Resolution resolution = getResolution( field );
        Class<?> type = field.getType();
        if( resolution == Resolution.NAME ) {
            String name = field.getName();
            return state.getValueByName( name );
        }
        return state.getValueByType( type );
    }

    private Resolution getResolution( Field field ) {
        Resolution resolution = getDeclaredResolution( field );
        if( resolution == Resolution.AUTO ) {
            return typeIsTooGeneric( field.getType() ) ? Resolution.NAME : Resolution.TYPE;
        }
        return resolution;
    }

    private Resolution getDeclaredResolution( Field field ) {
        for( Annotation annotation : field.getAnnotations() ) {
            if( annotation instanceof ScenarioState ) {
                return ( (ScenarioState) annotation ).resolution();
            }
            if( annotation instanceof ProvidedScenarioState ) {
                return ( (ProvidedScenarioState) annotation ).resolution();
            }
            if( annotation instanceof ExpectedScenarioState ) {
                return ( (ExpectedScenarioState) annotation ).resolution();
            }
        }
        throw new IllegalArgumentException( "Field " + field + " has no valid annotation" );
    }

    private boolean typeIsTooGeneric( Class<?> type ) {
        return type.isPrimitive()
                || type.getName().startsWith( "java.lang" )
                || type.getName().startsWith( "java.io" )
                || type.getName().startsWith( "java.util" );
    }

}
```
```
package jgiven;

import java.util.Collection;
import java.util.Map;

import com.google.common.collect.Maps;
import com.google.common.collect.Multimap;
import com.google.common.collect.Multimaps;
import com.tngtech.jgiven.Stage;

public class ValueInjectorState {
	private final Map<Class<?>, Object> valuesByType = Maps.newHashMap();
	private final Map<String, Object> valuesByName = Maps.newHashMap();

	// a map does not exactly work here because of duplicate keys, I did not
	// figure out what is exactly the best for this situation but google guava
	// multimap seems to fit the feature description
	private final Multimap<Class<?>, Stage> subscibedByType = Multimaps.newListMultimap(map, factory);
	private final Multimap<String, Stage> subscibedByName = Multimaps.newListMultimap(map, factory);

	public void subscribeByName(String name, Stage stage) {
		subscibedByName.put(name, stage);
	}

	public Collection<Stage> getSubscribers(String fieldName)
    {
    	return subscibedByName.get(fieldName);
    }

	public void unSubscribe() {
		// ...
	}

	public void updateValueByName(String name, Object value) {
		valuesByName.put(name, value);
	}

	public void updateValueByType(Class<?> type, Object value) {
		valuesByType.put(type, value);
	}

	public Object getValueByType(Class<?> type) {
		return valuesByType.get(type);
	}

	public Object getValueByName(String name) {
		return valuesByName.get(name);
	}
}
```

**Comment by koenusz** [comment] 2016-04-19 09:57
Just a suggestion, this does not even compile but I guess it should get the idea across.

**Comment by pityq** [comment] 2016-05-12 09:13
Is there any advancement on this issue (or on #202 for that matter)?

**Comment by albertofaci** [comment] 2016-05-12 09:17
@pityq I just pushed a revised version that mitigates the performance overhead that @janschaefer mentioned in #205

**Comment by janschaefer** [comment] 2016-05-12 09:46
Cool! I will try to have a look at that this evening, otherwise I will look at it tomorrow

**Comment by janschaefer** [comment] 2016-05-16 13:34
I close this as a duplicate of #202

**Closed by janschaefer** 2016-05-16 13:34 UTC
Labels: duplicate, enhancement, experimental
