### ISSUE TITLE
Searching HTML5 report on mobile phone doesn't work

### ISSUE THREAD

**Issue by ahus1** [TNG/JGiven#182] opened 2016-01-09 12:46 UTC
I observe the following **unexpected behavior:**

    Given JGiven's own report in version 0.11.0 on http://jgiven.org/jgiven-report/html5/ 
    When I open it my mobile phone (Android 5.1.1, with Chrome 47.0)
       and I open then menu 
       and I tap into the search field
    Then the menu closes 
       and I can't enter a search term.

Expected behavior: 

    Then the menu stays open 
       and the cursor is in the search field 
       and I am able to type the search term.

I was not able to reproduce the unexpected behavior on Google Chrome Desktop 47.0. 

Please have a look. Thanks!

**Comment by janschaefer** [comment] 2016-01-10 11:45
I thought that I have already fixed that issue, but apparently it is only fixed on desktop browsers.

**Closed** 2016-02-06 12:59 UTC
Labels: bug, HTML Report

**Comment by janschaefer** [comment] 2016-02-06 13:00
This issue is caused by an issue in angular-foundation. http://github.com/pineconellc/angular-foundation/issues/161. Fixed by a workaround that captures resize events when the mobile menu is shown.
